- name: Pool AspDockerApp
  hosts: staging
  become: true
  tasks:

  - name: stop all docker containers
    shell: docker stop $(docker ps -a -q)
    ignore_errors: true

  - name: remove all docker containers
    shell: docker rm $(docker ps -a -q)
    ignore_errors: true

  - name: Remove image
    docker_image:
      name: saintmember/aspdockerapp
      state: absent

  - name: Pull image
    docker_image:
      name: saintmember/aspdockerapp

  - name: Start saintmember/aspdockerapp
    shell: docker run -d -p 80:5000 saintmember/aspdockerapp
 
